# docker-compose.yml
services:
  memorial-sass-adm:
    build:
      context: .
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    container_name: memorial-sass-adm
    restart: always
    networks:
      - proxy
    ports:
      - "3010:3010" 
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}

networks:
  proxy:
    external: true
